runtime: nodejs10

instance_class: F1

automatic_scaling:
    max_instances: 1
    min_instances: 0
    target_cpu_utilization: 0.75
    max_idle_instances: 1
    min_idle_instances: 0

includes:
- env.yaml